Problem Statement

In [ ]:
##### The dataset is a fictional dataset from a Bank. The bank has seen an anusual churn rate. They want to understand what problem is and address the problem. 1 is not in the bank and 0 is still in the bank. We have to find rules and correlation to predict which customers have the higher chance of leaving the bank.

Dependencies

In [ ]:
import numpy as np
import pandas as pd
import tensorflow as tf
from sklearn.preprocessing import LabelEncoder
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import confusion_matrix, accuracy_score
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

Data Preprocessing

In [ ]:
# The first three columns are irrelevant and will not help in the prediction thus we dont need them in the X or Y
df = pd.read_csv("Churn_Modelling.csv")
X = df.iloc[:, 3:-1].values
y = df.iloc[:, -1].values

# Label Encoding Gender

Label Encoding Gender

In [ ]:
le = LabelEncoder()
# Take all the rows and the index two is the column gender
X[:, 2] = le.fit_transform(X[:, 2])

In [ ]:
# Perform Hot encoding in Geography Column

In [ ]:
ct = ColumnTransformer(transformers = [('encoder', OneHotEncoder(),[1])] , remainder ='passthrough' )
X = np.array(ct.fit_transform(X))

In [ ]:
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


In [ ]:
#Split into test and Train

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.2, random_state = 0)

# Feature Scaling

In [ ]:
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

Build The ANN

In [ ]:
# initializing the ANN
ann = tf.keras.models.Sequential()

In [ ]:
# Adding the input layer and the first hidden layer

In [ ]:
# How do we know how many neurons do we want
ann.add(tf.keras.layers.Dense(units=6, activation = 'relu'))

# Activate Second Hidden Layer

In [ ]:
ann.add(tf.keras.layers.Dense(units=6, activation = 'relu'))

# Add The Ouput Layer

In [ ]:
ann.add(tf.keras.layers.Dense(units=1, activation = 'sigmoid'))

# Training the ANN

In [ ]:
# Compile the ANN
# when performing binary classification the loss function is good to be
ann.compile(optimizer ='adam' , loss = 'binary_crossentropy', metrics = ['accuracy'] )

In [ ]:
# Train the ann with the training set

In [ ]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step - accuracy: 0.3920 - loss: 0.8693
Epoch 2/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.7923 - loss: 0.5235
Epoch 3/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7909 - loss: 0.4764
Epoch 4/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8011 - loss: 0.4435
Epoch 5/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8107 - loss: 0.4219
Epoch 6/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8253 - loss: 0.4044
Epoch 7/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.8302 - loss: 0.3908
Epoch 8/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8387 - loss: 0.3755
Epoch 9/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.8389 - loss: 0.3694
Epoch 10/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.8495 - loss: 0.3555
Epoch 11/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.8449 - loss: 0.3672
Epoch 12/100
250/250 ━━━━━━━━━━━━━━━━━━━━

In [ ]:
# Make prediction on a certain client to check the algo

In [ ]:
# Since we have encoded the values the 1, 0, 0 is the France value
# Since we have scaled all our values we have also to apply scaling to the input inside the square brackets
ann.predict(sc.transform([[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]]))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step


array([[0.01855651]], dtype=float32)

In [ ]:
print(ann.predict(sc.transform([[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]])) > 5)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step
[[False]]


In [ ]:
# Predicting Test Results

In [ ]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step
[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


In [ ]:
# Confusion Matrix Accuracy Test on the Testing Set

In [ ]:
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1514   81]
 [ 185  220]]


0.867